### ISSUE TITLE
Template Switcher Dialog

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#37]
We need a template switcher dialog for pages. The templates should be listed in a nice way and the dialog should handle the case when a page cannot switch its template at all.

**Comment by bastianallgeier** [comment]
I really like the way Notion displays the available templates for new pages …
![bildschirmfoto 2017-08-31 um 10 09 37](https://user-images.githubusercontent.com/24532/29913153-914567fc-8e34-11e7-80e8-62b5b6a603d6.png)

**Comment by distantnative** [comment]
@bastianallgeier 
How about removing the template selection from the "Add page" dialog? And instead of a dialog make it this full-page-notion-like-design. Once a template has been selected, the fieldset for the corresponding blueprint is loaded. When changing a template, fieldset fades out with the template selector displayed (or message that it cannot be changed, maybe even some templates disabled if it cannot be switched to them), when a template is selected, we get to another screen showing how the current content data would be affected (new fields, missing fields etc.). And then once confirmed, fieldset from ne template fades in. What do you think?

Also I like the idea that the default would just be listed blueprints/templates with name and subline, but if an image with the same name is added (either directly to the blueprints folder or in `assets/templates`), the image is shown as well like on Notion. This would give Developers a great chance to add visual representations to make it even easier for a client to chose the right template.

**Comment by distantnative** [comment]
First preview:
![kapture 2017-10-06 at 20 07 24](https://user-images.githubusercontent.com/3788865/31291991-fcd18b04-aad1-11e7-89d2-825d33496d28.gif)

**Comment by distantnative** [comment]
@bastianallgeier 
In this direction or do you also have a new visualisation for this review view in mind?

<img width="911" alt="screen shot 2017-10-06 at 20 59 34" src="https://user-images.githubusercontent.com/3788865/31293945-62501818-aad9-11e7-8ce1-763e6a36996a.png">

**Comment by distantnative** [comment]
Newly created pages without a selected template could be created as `_.txt` as name convention for template-less pages. When the panel encounters such a content file, the template selection is enforced before being able to edit any data.
